language: php
php:
  - "hhvm"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
before_script:
  - git clone --depth=50 --branch=master git://github.com/aimeos/arcavias-core.git ../arcavias-core
  - cd ../arcavias-core
  - mv ../ai-swiftmailer ext/
  - composer require "swiftmailer/swiftmailer" ">=4.0"
  - composer install
script: "vendor/bin/phing -Ddir=ext/ai-swiftmailer testext && vendor/bin/phing -Ddir=ext/ai-swiftmailer checkext"
