sudo: false
dist: xenial
language: php

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1

env:
  - VERSION=6.*
  - VERSION=5.*
  - VERSION=4.*

matrix:
  fast_finish: true

before_script:
  - git clone --depth=50 --branch=2020.07 git://github.com/aimeos/aimeos-core.git ../aimeos-core
  - cd ../aimeos-core && mv ../ai-swiftmailer ext/
  - travis_retry composer require "swiftmailer/swiftmailer" "${VERSION}"

script:
  - vendor/bin/phing -Ddir=ext/ai-swiftmailer coverageext checkext

after_success:
  - php vendor/bin/coveralls -c ext/ai-swiftmailer/.coveralls.yml
